#!/usr/bin/env python3
"""Initialize the 'wacker' graph with HVAC ontology from old SynapseOS.

Creates the instance DB at ~/.synapse/dbs/wacker/instance.db with:
- Full ontology (36 entity types, 38 relationship types)
- Domain-specific prompts for extraction, reasoning, enrichment, etc.
- Metadata (domain, language, etc.)

Usage:
    python scripts/init_wacker.py
"""

from __future__ import annotations

import json
from pathlib import Path

from synapse.storage.instance_store import InstanceStore

# ── Ontology ────────────────────────────────────────────────────

ENTITY_TYPES = {
    # Layer 1: Inventory
    "PRODUCT_FAMILY": "A product line of filter housings sharing common construction and purpose",
    "PRODUCT_VARIANT": "A specific pre-computed product configuration with fixed dimensions and properties",
    "DIMENSION_MODULE": "A standard width-by-height size configuration used across product families",
    "MATERIAL": "A construction material grade with corrosion resistance rating",
    "VARIANT_LENGTH": "An available housing depth/length option for a product family",
    "OPTION": "A selectable configuration option for a product (door hinging, connection, lock, etc.)",
    "FEATURE": "A physical capability or built-in characteristic of a product",
    "ACCESSORY": "An add-on accessory compatible with one or more product families",
    "FILTER_CONSUMABLE": "A compatible filter element that can be installed in a housing",
    "CONSUMABLE": "A replacement or spare part suggested for ongoing maintenance",
    "DUCT_CONNECTION": "A rectangular-to-round duct transition adapter",
    "MOUNTING_SYSTEM": "A method for mounting filters inside a housing",
    "DOCUMENT_SOURCE": "A source document from which product data was extracted",
    "CATEGORY": "A classification group for products or variants",
    "COMPETITOR_PRODUCT": "A competitor product for cross-referencing and replacement suggestions",
    # Layer 2: Domain Physics
    "APPLICATION": "A business context or building type that determines environmental stressors and material requirements",
    "ENVIRONMENT": "A physical installation environment with temperature, humidity, and exposure characteristics",
    "ENVIRONMENTAL_STRESSOR": "A physical or chemical attack vector produced by an environment or application that demands countermeasure traits",
    "PHYSICAL_TRAIT": "A capability or characteristic of a product family or material that can neutralize or resist an environmental stressor",
    "SUBSTANCE": "A contaminant substance generated by an application or environment",
    "RISK": "A potential failure mode that can occur when stressors interact with unsuitable products or materials",
    "REGULATION": "A regulatory standard or compliance requirement that applies to specific applications",
    "REQUIREMENT": "A technical requirement derived from an application context or regulation",
    "SOLUTION": "A mitigation measure that can be applied to reduce or eliminate a risk",
    "SIZING_RULE": "A physics-based formula used to validate product sizing against engineering limits",
    "DEPENDENCY_RULE": "A rule that triggers a multi-stage assembly when a stressor requires a protective pre-stage before the target product",
    "HARD_CONSTRAINT": "A physical limit on a product parameter that cannot be overridden by the user",
    "INSTALLATION_CONSTRAINT": "A rule that blocks or warns about product-environment combinations based on space, material, or physics limits",
    "GEOMETRIC_CONSTRAINT": "A physical dimension constraint on product options or accessories",
    "FUNCTIONAL_GOAL": "A high-level user intent that maps to required physical traits for product selection",
    "COMPATIBILITY_RULE": "A rule defining physical compatibility between filters and housings",
    # Layer 3: Playbook
    "LOGIC_GATE": "A conditional physics check that monitors an environmental stressor and evaluates whether a risk threshold is crossed",
    "PARAMETER": "An input parameter that the system needs to collect from the user to complete product selection or evaluate a LogicGate",
    "QUESTION": "A reusable question text template for collecting a specific Parameter from the user",
    "CLARIFICATION_RULE": "A contextual rule that fires when a specific application or environment is detected, demanding additional parameters",
    "VARIABLE_FEATURE": "A configurable product feature that requires user selection or can be auto-resolved from a default value",
    "FEATURE_OPTION": "A discrete selectable option for a VariableFeature, with physics rationale and recommendation flags",
    "DISCRIMINATOR": "A diagnostic question that helps the system decide which FeatureOption to recommend",
    "STRATEGY": "A response strategy triggered by a detected risk or used for product sizing optimization",
    "CAPACITY_RULE": "An airflow capacity formula for a specific product family and module size",
    "SIZE_PROPERTY": "A size-specific property value for a product family, used for weight lookups at specific size/length intersections",
    # Layer 4: Session (runtime)
    "SESSION": "Root node for a user interaction session, keyed by UUID",
    "ACTIVE_PROJECT": "The current project configuration within a session, storing locked parameters and resolved state",
    "TAG_UNIT": "An individual tag/item specification within a project, representing one physical product unit being configured",
    "CONVERSATION_TURN": "An individual message in the conversation history",
    "EXPERT_REVIEW": "An expert review or automated judge annotation evaluating conversation quality",
}

RELATIONSHIP_TYPES = {
    # Layer 1: Inventory
    "AVAILABLE_IN_SIZE": "Product family is available in this dimension module",
    "AVAILABLE_IN_MATERIAL": "Product family is available in this material grade",
    "HAS_LENGTH_VARIANT": "Product family has this housing depth option",
    "HAS_OPTION": "Product family supports this optional configuration",
    "HAS_DEFAULT_OPTION": "Product family includes this option as standard/default",
    "INCLUDES_FEATURE": "Product family has this feature built in",
    "HAS_COMPATIBLE_ACCESSORY": "Product family is compatible with this accessory",
    "INCOMPATIBLE_WITH": "Product family is NOT compatible with this accessory",
    "NOT_COMPATIBLE_WITH": "Accessory is not compatible with a specific product family",
    "USES_MOUNTING_SYSTEM": "Product family uses this filter mounting method",
    "SUGGESTS_CROSS_SELL": "Product family suggests purchasing this related item",
    "IS_CATEGORY": "Variant belongs to a classification category",
    "FROM_DOCUMENT": "Data was extracted from this source document",
    "ACCEPTS_FILTER": "Product variant accepts this filter consumable",
    "COMPATIBLE_WITH_DUCT": "Product variant is compatible with this duct transition",
    "REQUIRES_VARIANT": "Option requires a specific length variant",
    "CROSS_REFERENCES": "Competitor product maps to our equivalent",
    # Layer 2: Physics
    "EXPOSES_TO": "Application or environment produces/exposes to an environmental stressor",
    "IS_A": "Environment hierarchy — child environment inherits parent stressors",
    "GENERATES": "Application or environment generates a contaminant substance",
    "HAS_RISK": "Application or environment carries an inherent risk",
    "REQUIRES_COMPLIANCE": "Application requires compliance with a regulation",
    "REQUIRES_RESISTANCE": "Application requires a specific material resistance level",
    "MAY_BE_ENVIRONMENT": "Application may involve a specific environment type",
    "DEMANDS_TRAIT": "Environmental stressor demands a physical trait for safe operation (core causal rule)",
    "NEUTRALIZED_BY": "Physical trait is rendered ineffective by an environmental stressor",
    "CAUSES": "Substance or environment causes a specific risk",
    "MITIGATED_BY": "Risk can be mitigated by a feature or solution",
    "TRIGGERS_STRATEGY": "Risk triggers a specific response strategy",
    "VULNERABLE_TO": "Product family or material is vulnerable to a risk or substance",
    "PRONE_TO": "Product family has a tendency toward a specific risk",
    "PROTECTS_AGAINST": "Product family provides built-in protection against a risk",
    "SUITABLE_FOR": "Product family is suitable for a specific environment",
    "INEFFECTIVE_AGAINST": "Product family cannot handle a specific substance",
    "HAS_TRAIT": "Product family possesses a physical trait directly",
    "PROVIDES_TRAIT": "Material provides a physical trait to products made from it",
    "MEETS_REQUIREMENT": "Material satisfies a technical requirement",
    "COMPLIES_WITH": "Material complies with a regulation",
    "HAS_SIZING_RULE": "Product family uses this sizing physics formula",
    "HAS_HARD_CONSTRAINT": "Product family has this non-overridable physical limit",
    "HAS_INSTALLATION_CONSTRAINT": "Product family has this installation restriction",
    "TRIGGERED_BY_STRESSOR": "Dependency rule is triggered when this stressor is detected",
    "UPSTREAM_REQUIRES_TRAIT": "Dependency rule requires this trait in the upstream stage",
    "DOWNSTREAM_PROVIDES_TRAIT": "Dependency rule expects this trait from the downstream stage",
    "REQUIRES_TRAIT": "Functional goal requires this physical trait",
    "APPLIES_TO": "Compatibility rule applies to specific product variants",
    # Layer 3: Playbook
    "REQUIRES_DATA": "A LogicGate requires specific Parameters to be collected before evaluation",
    "MONITORS": "A LogicGate monitors a specific EnvironmentalStressor",
    "TRIGGERS_GATE": "An Application or Environment context activates a LogicGate",
    "ASKED_VIA": "A Parameter is collected via a specific Question template",
    "REQUIRES_PARAMETER": "A ProductFamily requires specific Parameters to be resolved",
    "DEMANDS_PARAMETER": "A ClarificationRule demands a specific Parameter",
    "TRIGGERED_BY_CONTEXT": "A ClarificationRule is triggered by a specific Application context",
    "APPLIES_TO_PRODUCT": "A ClarificationRule applies to specific ProductFamily nodes",
    "HAS_VARIABLE_FEATURE": "A ProductFamily has a configurable VariableFeature",
    "SELECTION_DEPENDS_ON": "A VariableFeature's selection depends on a Discriminator question",
    "OPTIMIZATION_STRATEGY": "A ProductFamily uses a specific sizing/layout optimization Strategy",
    "HAS_CAPACITY": "A ProductFamily has a CapacityRule defining airflow per module",
    # Layer 4: Session
    "WORKING_ON": "Links a Session to its active project",
    "HAS_UNIT": "Links an ActiveProject to its TagUnit specifications",
    "HAS_TURN": "Links an ActiveProject to its ConversationTurn history",
    "HAS_REVIEW": "Links an ActiveProject to expert review annotations",
    "USES_MATERIAL": "Links ActiveProject to a Material node when material is locked",
    "TARGETS_FAMILY": "Links ActiveProject to a ProductFamily node",
    "SIZED_AS": "Links a TagUnit to a DimensionModule node",
}

# ── Format helpers ──────────────────────────────────────────────

def _fmt_entity_types() -> str:
    return "\n".join(f"- {k}: {v}" for k, v in sorted(ENTITY_TYPES.items()))

def _fmt_relationship_types() -> str:
    return "\n".join(f"- {k}: {v}" for k, v in sorted(RELATIONSHIP_TYPES.items()))

# ── Prompts ─────────────────────────────────────────────────────

PROMPTS = {

"entity_extraction_system": f"""You are an expert HVAC knowledge extraction system for Wacker filter housing products.
You extract structured entities from technical documents about HVAC filter housings, materials, accessories, and applications.

ENTITY TYPES (extract ONLY these types):
{_fmt_entity_types()}

RULES:
1. Extract every entity mentioned in the text that matches one of the types above.
2. For each entity, provide: "text" (exact mention), "entity_type", "confidence" (0.0-1.0), "properties" (dict of key attributes).
3. Normalize product codes: GDP, GDB, GDMI, GDC, PFF are PRODUCT_FAMILY names.
4. Material codes: FZ (galvanized steel), AZ (aluzinc), RF (stainless V2A), SF (stainless V4A), ZM (ZnMgAl coated).
5. Dimensions: extract as DIMENSION_MODULE with width_mm and height_mm properties.
6. Be precise — prefer specific types (PRODUCT_VARIANT over PRODUCT_FAMILY when a specific config is mentioned).
7. Extract quantities, ratings, and specifications as properties, not separate entities.
8. Do NOT extract generic words, verbs, or sentence fragments as entities.""",

"entity_extraction_user": """Extract all entities from the following document section.

SECTION TEXT:
{section_text}

Return a JSON object:
{{
  "entities": [
    {{"text": "exact text", "entity_type": "TYPE", "confidence": 0.9, "properties": {{}}}},
    ...
  ]
}}

Return ONLY the JSON, nothing else.""",

"relationship_extraction_system": f"""You are an expert HVAC knowledge extraction system.
You extract relationships between entities in technical documents about filter housings, materials, and applications.

RELATIONSHIP TYPES (extract ONLY these):
{_fmt_relationship_types()}

RULES:
1. Extract relationships between entities found in the text.
2. Both subject and object must be real entities with known types.
3. The predicate must be one of the relationship types listed above.
4. Provide confidence scores — higher for explicitly stated relationships, lower for implied ones.
5. Pay special attention to:
   - Product → Material compatibility (AVAILABLE_IN_MATERIAL)
   - Product → Size availability (AVAILABLE_IN_SIZE)
   - Application → Stressor chains (EXPOSES_TO)
   - Stressor → Trait demands (DEMANDS_TRAIT)
   - Material → Trait provisions (PROVIDES_TRAIT)
6. Do NOT invent relationships not supported by the text.""",

"relationship_extraction_user": """Extract all relationships from the following document section.
Use ONLY entities that appear in the text or were previously extracted.

SECTION TEXT:
{section_text}

ENTITIES FOUND IN THIS SECTION:
{entities_json}

Return a JSON object:
{{
  "relationships": [
    {{"subject": "entity text", "subject_type": "TYPE", "predicate": "REL_TYPE", "object": "entity text", "object_type": "TYPE", "confidence": 0.9}},
    ...
  ]
}}

Return ONLY the JSON.""",

"reasoning_system": f"""You are a knowledge graph reasoning agent for Wacker HVAC filter housing products.
You answer questions by querying a FalkorDB knowledge graph containing product catalogs, material specifications, application environments, and engineering rules.

TOOLS (use exactly ONE per step):
1. GRAPH_QUERY(cypher) — execute a read-only Cypher query
2. SECTION_TEXT(section_id) — retrieve full text of a document section
3. ANSWER(text) — provide the final answer (terminates reasoning)

KNOWLEDGE GRAPH SCHEMA:
Node types: {_fmt_entity_types()}

Relationship types: {_fmt_relationship_types()}

All entity nodes have a `canonical_name` property (lowercase, normalized).

DOMAIN KNOWLEDGE:
- Product families: GDP (bag filter housing), GDB (compact filter housing), GDMI (HEPA housing), GDC (carbon filter housing), PFF (pre-filter frame)
- Materials: FZ (galvanized, C3), AZ (aluzinc, C4), RF (V2A stainless, C4), SF (V4A stainless, C5), ZM (ZnMgAl, C4+)
- Key causal chain: APPLICATION → EXPOSES_TO → STRESSOR → DEMANDS_TRAIT → PHYSICAL_TRAIT
- Risk chain: SUBSTANCE → CAUSES → RISK → MITIGATED_BY → SOLUTION

CYPHER SYNTAX RULES:
- Write raw Cypher directly inside parentheses. NO quotes around the query.
- Always use toLower() and CONTAINS for entity matching.
- Only read queries (MATCH ... RETURN). Never use CREATE, DELETE, SET, MERGE.

REASONING STRATEGY:
1. ONE action per step. Keep Thought to 1-2 sentences.
2. Start broad: query ALL neighbors of key entities first.
3. Follow causal chains: Application → Stressor → Trait → Product/Material.
4. For product selection questions, check both product traits AND material traits.
5. When you have enough information, immediately use ANSWER().
6. Cite specific entities and relationships from the graph.
7. Budget: ~12 steps max.

FORMAT:
Thought: [1-2 sentences]
Action: GRAPH_QUERY(MATCH ...)
— or —
Action: ANSWER(your final answer)""",

"reasoning_user": """{conversation_context}USER QUESTION: {question}

RELEVANT SECTIONS (from tree search):
{section_summaries}

Think step by step. Use GRAPH_QUERY to explore the knowledge graph. When you have enough information, use ANSWER.
If prior turns already fetched relevant data, reuse it instead of re-querying.""",

"tree_search_system": "You are a document section retrieval expert for HVAC technical documentation.",

"tree_search_user": """You are given a query and the document tree structures from HVAC product catalogs and technical documentation.

Query: {query}

Document trees:
{document_trees}

Which sections are most likely to contain information relevant to this query?
Consider: product specifications, material tables, application guides, sizing rules, and accessory lists.

Return a JSON object with:
- "thinking": your reasoning
- "sections": array of section node_ids (e.g., ["0003", "0007"])

Return ONLY the JSON, nothing else.""",

"self_assessment_system": "You are a critical evaluator of AI-generated answers about HVAC filter housing products.",

"self_assessment_user": """Evaluate the following AI-generated answer about HVAC products for quality and reliability.

QUESTION: {question}

ANSWER: {answer}

EVIDENCE USED (from reasoning trace):
{evidence_summary}

Assess the answer on these dimensions:
1. **confidence** (0.0-1.0): How confident are you that the answer is correct?
2. **groundedness** (0.0-1.0): What fraction of claims are supported by evidence from the graph?
3. **completeness** (0.0-1.0): Does the answer fully address the question?
4. **reasoning**: A 1-2 sentence explanation.
5. **gaps**: Specific knowledge gaps that would improve the answer.

Return a JSON object with keys: "confidence", "groundedness", "completeness", "reasoning", "gaps".
Return ONLY the JSON.""",

"enrichment_system": "You are an expert HVAC knowledge extraction system for Wacker filter products.",

"enrichment_user": f"""Extract entities and relationships from the following AI-generated answer about HVAC products.

ANSWER TEXT:
{{answer_text}}

ORIGINAL QUESTION:
{{question}}

ENTITY TYPES:
{_fmt_entity_types()}

RELATIONSHIP TYPES:
{_fmt_relationship_types()}

ENTITIES ALREADY IN THE GRAPH (do NOT re-extract):
{{existing_entities}}

RULES:
1. Extract ONLY new entities and relationships NOT already in the graph.
2. Each entity: "text", "entity_type", "confidence"
3. Each relationship: "subject", "subject_type", "predicate", "object", "object_type", "confidence"
4. Only factual knowledge — skip opinions or hedging.
5. Pay attention to product-material compatibility, stressor-trait chains, and sizing data.

Return JSON: {{"entities": [...], "relationships": [...]}}
Return ONLY the JSON.""",

"compaction_system": "You are a conversation summarizer for an HVAC product knowledge graph reasoning system.",

"compaction_user": """Summarize the following conversation turns into a compact context block.

CONVERSATION TURNS:
{turns_text}

Write a structured summary:
- **Goal**: What is the user trying to find out?
- **Key entities**: Product families, materials, applications, stressors discovered
- **Graph data fetched**: Important facts from the knowledge graph
- **Established context**: Resolved references (e.g., "the material = SF (V4A stainless)")

RULES:
1. Keep it concise — under 300 words.
2. Preserve ALL entity names, product codes, and material grades exactly.
3. Include Cypher patterns that returned useful data.
4. Write in the same language as the conversation.""",

}

BOILERPLATE_KEYWORDS = [
    "table of contents", "spis treści", "inhaltsverzeichnis",
    "copyright", "all rights reserved", "alle rechte vorbehalten",
    "disclaimer", "legal notice", "impressum",
    "page", "seite", "strona",
    "www.wfriedrich.de", "wacker",
]

# ── Main ────────────────────────────────────────────────────────

def main():
    db_dir = Path.home() / ".synapse" / "dbs" / "wacker"
    db_dir.mkdir(parents=True, exist_ok=True)
    db_path = db_dir / "instance.db"

    store = InstanceStore(db_path)

    # Create ontology version
    version_id = store.create_ontology_version(
        name="wacker-hvac-v1",
        description="Full HVAC ontology from old SynapseOS (4-layer architecture: Inventory, Physics, Playbook, Session)",
        domain="HVAC Filter Housing Systems",
        activate=True,
    )
    print(f"Created ontology version {version_id}")

    # Store entity types
    store.store_entity_types_batch(version_id, ENTITY_TYPES)
    print(f"Stored {len(ENTITY_TYPES)} entity types")

    # Store relationship types
    store.store_relationship_types_batch(version_id, RELATIONSHIP_TYPES)
    print(f"Stored {len(RELATIONSHIP_TYPES)} relationship types")

    # Store prompts
    for key, text in PROMPTS.items():
        store.store_prompt(version_id, key, text)
    print(f"Stored {len(PROMPTS)} prompts")

    # Store boilerplate keywords
    store.store_prompt(
        version_id,
        "boilerplate_keywords",
        json.dumps(BOILERPLATE_KEYWORDS, ensure_ascii=False),
        description="Keywords indicating boilerplate sections to skip",
    )

    # Set metadata
    store.set_meta("domain", "HVAC Filter Housing Systems")
    store.set_meta("subdomain", "Industrial air filtration, product configuration, material selection")
    store.set_meta("language", "German/English")
    store.set_meta("document_types", json.dumps(["product catalogs", "technical datasheets", "application guides", "sizing tables"]))
    store.set_meta("key_topics", json.dumps([
        "filter housing product families (GDP, GDB, GDMI, GDC, PFF)",
        "material grades and corrosion resistance",
        "environmental applications and stressors",
        "product sizing and airflow capacity",
        "accessories and mounting systems",
        "multi-stage assembly rules",
    ]))
    store.mark_bootstrapped("HVAC Filter Housing Systems")

    # Log to activity log
    items = []
    for etype, desc in ENTITY_TYPES.items():
        items.append(("entity_type", etype, desc))
    for rtype, desc in RELATIONSHIP_TYPES.items():
        items.append(("relationship_type", rtype, desc))
    for key in PROMPTS:
        items.append(("prompt", key, ""))
    store.log_activity_batch("init", f"v{version_id}", "Init: HVAC (Wacker import)", items)

    store.close()

    print(f"\nDone! Instance DB: {db_path}")
    print(f"  Entity types: {len(ENTITY_TYPES)}")
    print(f"  Relationship types: {len(RELATIONSHIP_TYPES)}")
    print(f"  Prompts: {len(PROMPTS) + 1}")
    print(f"\nUse: synapse -g wacker status")
    print(f"     synapse -g wacker ingest <docs>")


if __name__ == "__main__":
    main()
